version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: if0_36633679_XXX
      MYSQL_USER: if0_36633679
      MYSQL_PASSWORD: JaxGtP1VNZ2hSPq
    ports:
      - "3306:3306"
